name: CI

on: [push, pull_request]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - name: Set up JDK 21
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
      with:
        distribution: 'adopt'
        java-version: '21'
        cache: 'gradle'

    - name: Start docker container
      env:
        TZ: "Asia/Tokyo"
      run: docker compose up -d

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
    - uses: gradle/wrapper-validation-action@b231772637bb498f11fdbc86052b6e8a8dc9fc92 # v2.1.2

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: create table on database
      env:
        TZ: "Asia/Tokyo"
      run: ./gradlew flywayMigrate

    - name: execute jOOQ code generator
      run: ./gradlew jooqCodegen

    - name: execute OpenAPI code generator
      run: ./gradlew openApiGenerate

    - name: Check
      run: ./gradlew check
